# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "400fdce51287067c5f56249c70a1d23e"
name = "Visual Search"
handle = "visual-search-9"
application_url = "https://presented-cordless-browse-nicaragua.trycloudflare.com"
embedded = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://presented-cordless-browse-nicaragua.trycloudflare.com/auth/callback",
  "https://presented-cordless-browse-nicaragua.trycloudflare.com/auth/shopify/callback",
  "https://presented-cordless-browse-nicaragua.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true
