# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e55c302da4aa157a5b7b2573695dbff8"
organization_id = "164642336"
name = "visual-search-dev"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes,write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
