# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "400fdce51287067c5f56249c70a1d23e"
name = "Visual Search"
handle = "visual-search-9"
application_url = "https://pump-floor-danish-rh.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://pump-floor-danish-rh.trycloudflare.com/auth/callback",
  "https://pump-floor-danish-rh.trycloudflare.com/auth/shopify/callback",
  "https://pump-floor-danish-rh.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
