# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bccd4eff33005ba9881ed243e7af66d3"
name = "Visual Search - B"
handle = "visual-search-b"
application_url = "https://minute-ted-widely-returned.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://minute-ted-widely-returned.trycloudflare.com/auth/callback",
  "https://minute-ted-widely-returned.trycloudflare.com/auth/shopify/callback",
  "https://minute-ted-widely-returned.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
